force-app/main/default/objects/Job_Applications__c/Job_Applications__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Applications Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Applications__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Applications__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JoobleIntegrationTest.cls
@isTest
public with sharing class JoobleIntegrationTest {
    @isTest
    static void testRetrieveJobs() {

    Test.setMock(HttpCalloutMock.class, new JoobleIntegrationMock(200, 'OK', getMockResponse()));
 
        // Define the keywords and location
        String keywords = 'Salesforce Developer';
        String location = 'Remote';

        // Call the retrieveJobs method
        JoobleIntegration.retrieveJobs(keywords, location);

        List<Job_Applications__c> jobApps = [SELECT Status__c, Name, Company_Name__c, Description__c FROM Job_Applications__c];
        System.assertEquals(1, jobApps.size());
        Job_Applications__c jobApp = jobApps[0];
        System.assertEquals('Saved', jobApp.Status__c);
        System.assertEquals('Job Title', jobApp.Name);
        System.assertEquals('Company Name', jobApp.Company_Name__c);
        System.assertEquals('Description', jobApp.Description__c);
    }

    // Return the mock response as a JSON string
    static String getMockResponse() {
        return '{"jobs": ['
            + '{}'
            + ']}';
    }
}