force-app/main/default/objects/Job_Applications__c/Job_Applications__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Applications Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Applications__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CleanupStaleJobApplications.cls
public with sharing class CleanupStaleJobApplications {

    public static void cleanupStaleJobApps(){
    // Calculate the date 30 days ago
    Date thirtyDaysAgo = System.today().addDays(-30);

    // Query the Job Apps
    List<Job_Applications__c> staleJobApplications = [SELECT Id FROM Job_Applications__c
                                                     WHERE Status__c NOT IN ('Closed', 'Accepted')
                                                     AND LastModifiedDate > :thirtyDaysAgo];

    System.debug('Stale Job Applications: ' + staleJobApplications);

    if (!staleJobApplications.isEmpty()) {
        List<Job_Applications__c> applicationsToUpdate = new List<Job_Applications__c>();

        for (Job_Applications__c jobApp : staleJobApplications) {
            // Update status to Closed and add a note
            jobApp.Status__c = 'Closed';
            jobApp.Notes__c = 'Closed by automated process.';
            applicationsToUpdate.add(jobApp);
        }

        try{
            if (!applicationsToUpdate.isEmpty()) {
                update applicationsToUpdate;
            }
        }
       catch(DmlException de){
            System.debug(de.getMessage());
       }
     }
    }
}