force-app/main/default/objects/Contact/fields/Job_Application_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Job_Application_Contacts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for Contact to Job Application</description>
    <label>Job Application Contacts</label>
    <referenceTo>Job_Applications__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application_Contacts__c/Job_Application_Contacts__c.object-meta.xml
<CustomObject>
    <label>Job Application Contact</label>
    <nameField>
        <label>Job Application Contacts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Application Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application_Contacts__c/fields/Job_Applications__c.field-meta.xml
<CustomField>
    <fullName>Job_Applications__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Applications</label>
    <referenceTo>Job_Applications__c</referenceTo>
    <relationshipLabel>Job Application Contacts</relationshipLabel>
    <relationshipName>Job_Application_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Applications__c/Job_Applications__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Applications Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Applications__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Applications__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerHandler.cls
public with sharing class JobApplicationTriggerHandler extends TriggerHandler{

    private List<Job_Applications__c> jobAppList;
    private List<Job_Applications__c> oldjobAppList;
    private Map<Id, Job_Applications__c> jobAppOldMap;
    private Map<Id, Job_Applications__c> jobAppNewMap;

    public JobApplicationTriggerHandler() {

        this.jobAppList = (List<Job_Applications__c>)Trigger.new;
        this.jobAppNewMap = (Map<Id, Job_Applications__c>)Trigger.newMap;
        this.jobAppOldMap = (Map<Id, Job_Applications__c>)Trigger.oldMap;
        this.oldjobAppList = (List<Job_Applications__c>)Trigger.old;
    }

    
    
    public override void afterInsert()
    {
         // Create a new Task for newly inserted job application
         List<Task> tasks = new List<Task>();
        
         for (Job_Applications__c jobApp : this.jobAppList){

             Task tsk = new Task();
             tsk.Subject = 'Make a follow-up Call';
             tsk.WhatId = jobApp.Id;
             tsk.WhoId = jobApp.Primary_Contact__c;
             tsk.OwnerId = jobApp.OwnerId;
             tsk.ActivityDate = Date.today().addDays(7);
             tasks.add(tsk);
         }
             insert tasks;

    }

    
    //automation to set the primary contact on the job application if the primary contact is null
    public override void beforeUpdate()
    {

        Set<Id> jobAppIds = new Set<Id>();
        for(Job_Applications__c job : this.jobAppList){
            jobAppIds.add(job.Id);
        }
    
        Map<Id, Contact> contacts = new Map<Id, Contact>([SELECT Id, LastName, Job_Application_Contacts__r.Id  FROM Contact WHERE Job_Application_Contacts__r.Id IN :jobAppIds]);
        Map<Id, Contact> jobIdToContact = new Map<Id, Contact>();

        for (Contact cont : contacts.values()) {
            if (!jobIdToContact.containsKey(cont.Job_Application_Contacts__r.Id)) {
                jobIdToContact.put(cont.Job_Application_Contacts__r.Id, cont);
            }
        }

        for(Job_Applications__c jobApp : this.jobAppList){
            if(jobApp.Primary_Contact__c == null){
                if (jobIdToContact.containsKey(jobApp.Id)){
                    jobApp.Primary_Contact__c = jobIdToContact.get(jobApp.Id).Id;
                }
            }
        }
       
    }
   

    public override void afterUpdate()
    {

         // Create a new Task for a job application Status changes
        List<Task> tasks = new List<Task>();
            
        for (Job_Applications__c jobApp : this.jobAppList)
        { 
            if(jobApp.Status__c == 'Applying')
            {
                tasks =  JobApplicationHelper.tasksWhenApplying(tasks,jobApp);
            }
            else if(jobApp.Status__c == 'Applied')
            {
                tasks =  JobApplicationHelper.tasksWhenApplied(tasks,jobApp);
            }
            else if(jobApp.Status__c == 'Accepted')
            {
                tasks =  JobApplicationHelper.tasksWhenAccepted(tasks,jobApp);
            }
            else if(jobApp.Status__c == 'Closed')
            {
                tasks =  JobApplicationHelper.tasksWhenAccepted(tasks,jobApp);
            }
         }
             if(!tasks.isEmpty())
             {
                insert tasks;
             }
             
    }
   
    public override void afterDelete()
    {}
   
    public override void afterUndelete()
    {}
    public override void beforeDelete()
    {}
    public override void beforeInsert()
    {}
   
}